platform :ios,              '6.1'

pod 'OBConnection',         '~> 2.2.0'
pod 'SDWebImage',           '~> 3.4'
pod 'Mantle',               '~> 1.0'
pod 'UIActivityIndicator-for-SDWebImage', '~> 1.0.0'

inhibit_all_warnings!
